[package]
name = "example_project"
version = "0.1.0"
authors = ["Jasper Visser <jasperav@hotmail.com>"]
edition = "2018"
description = "Example dir for the ORM for Scylla, fully compatible with Apache Cassandra™"
repository = "https://github.com/Jasperav/catalytic"
readme = "../../README.md"
keywords = ["database", "scylla", "cql", "cassandra"]
categories = ["database"]
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
catalytic_table_to_struct = { version = "0.1", path = "../../catalytic_table_to_struct" }
catalytic = { version = "0.1", path = "../../catalytic" }
dotenv = "0.15.0"

[dependencies]
scylla = "0.4.5"
tracing = "0.1.34"
catalytic_macro = { version = "0.1", path = "../../catalytic_macro" }
catalytic = { version = "0.1", path = "../../catalytic" }
tokio = "1.18.2"
serde_json = "1.0.81"
serde = "1.0.137"
uuid = "1.0.0"
trybuild = "1.0.61"
futures-util = "0.3.21"
tracing-subscriber = "0.3.11"
