[package]
name = "catalytic"
version = "0.1.3"
edition = "2018"
authors = ["Jasper Visser <jasperav@hotmail.com>"]
description = "ORM for Scylla, fully compatible with Apache Cassandra™"
repository = "https://github.com/Jasperav/catalytic"
readme = "../README.md"
keywords = ["database", "scylla", "cql", "cassandra"]
categories = ["database"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = "0.5.0"
once_cell = "1.10.0"
heck = "0.4.0"
uuid = "1.0.0"
tokio = { version = "1.18.2", features = ["time", "rt-multi-thread", "io-util"] }
tracing = "0.1.34"
thiserror = "1.0.31"
futures-util = "0.3.21"
