name: Scylla

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    # Locally scylla can be started like so: docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla
    services:
      scylladb:
        image: scylladb/scylla:5.4
        ports:
          - 9042:9042
          - 19042:19042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v2
      - name: Install stable 1.81
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          default: true
          components: rustfmt, clippy
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Run tests
        run: cargo test --all
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy check
        run: cargo clippy --tests -- -D warnings